# Generated by Django 4.2.5 on 2023-09-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.PositiveIntegerField(default=0, verbose_name='идентификатор чата в телеграм'),
        ),
    ]
