# Generated by Django 4.2.5 on 2023-09-21 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PleasantHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='место')),
                ('date_time', models.DateTimeField(verbose_name='время привычки')),
                ('action', models.CharField(max_length=150, verbose_name='действие')),
                ('interval', models.CharField(choices=[('Ежедневно', 'Ежедневно'), ('Один раз в неделю', 'Один раз в неделю'), ('Два раз в неделю', 'Два раз в неделю'), ('Три раз в неделю', 'Три раз в неделю'), ('Четыре раз в неделю', 'Четыре раз в неделю'), ('Пять раз в неделю', 'Пять раз в неделю'), ('Шесть раз в неделю', 'Шесть раз в неделю')], default='Ежедневно', max_length=19, verbose_name='периодичность')),
                ('execution_time', models.TimeField(verbose_name='время выполнения')),
                ('is_published', models.BooleanField(default=False, verbose_name='время выполнения')),
                ('habit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец привычки')),
            ],
            options={
                'verbose_name': 'полезная привычка',
                'verbose_name_plural': 'полезные привычки',
                'ordering': ('habit_user',),
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='статус')),
                ('last_try', models.DateTimeField(auto_now_add=True, verbose_name='попытка')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.pleasanthabit', verbose_name='привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информации',
            },
        ),
    ]
