# Generated by Django 4.2.5 on 2023-09-24 14:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pleasanthabit',
            options={'ordering': ('habit_user',), 'verbose_name': 'приятная привычка', 'verbose_name_plural': 'приятные привычки'},
        ),
        migrations.RemoveField(
            model_name='pleasanthabit',
            name='interval',
        ),
        migrations.AlterField(
            model_name='pleasanthabit',
            name='execution_time',
            field=models.DurationField(default=datetime.timedelta(seconds=120), help_text='Введите время в секундах. Максимальное время — 120 сек.', verbose_name='время выполнения'),
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='место')),
                ('date_time', models.DateTimeField(verbose_name='время привычки')),
                ('action', models.CharField(max_length=150, verbose_name='действие')),
                ('interval', models.CharField(choices=[('Ежедневно', 'Ежедневно'), ('Один раз в 2 дня', 'Один раз в 2 дня'), ('Один раз в 3 дня', 'Один раз в 3 дня'), ('Один раз в 4 дня', 'Один раз в 4 дня'), ('Один раз в 5 дней', 'Один раз в 5 дней'), ('Один раз в 6 дней', 'Один раз в 6 дней'), ('Один раз в 7 дней', 'Один раз в 7 дней')], default='Ежедневно', max_length=17, verbose_name='периодичность')),
                ('execution_time', models.DurationField(default=datetime.timedelta(seconds=120), help_text='Введите время в секундах. Максимальное время — 120 сек.', verbose_name='время выполнения')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='вознаграждение')),
                ('is_published', models.BooleanField(default=False, verbose_name='статус')),
                ('habit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец привычки')),
                ('pleasant_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.pleasanthabit', verbose_name='полезная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
                'ordering': ('habit_user',),
            },
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='привычка'),
        ),
    ]
